# markdown 
markdown: kramdown
highlighter: rouge

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: "Management.cio.gov"
description: "Guidance, Resources, and Artifacts to assist agencies in implementing FITARA and other related policies"
baseurl: https://management.cio.gov/
# Uncomment the following line for localhost development at http://127.0.0.1:4000/software/
# baseurl: /software

# GitHub information
org_name: WhiteHouse
repo_name: CIOmanagement
branch: gh-pages

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /
- text: Implementation Guidance
  url: /implementation/
- text: Policy Resources
  url: /policy/
- text: FAQ
  url: /faq/
- text: Schemas
  url: /schema/
- text: Community
  url: /community/
- text: Agency Plans
  url: /plans/

# sass
sass:
  sass_dir: _sass
